# Generated by Django 4.2.7 on 2023-11-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='products',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
